services:
  web:
    build: .
    container_name: activedir_web
    env_file: .env.docker.local
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 1433
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
